package com.softdesign.devintensive.utils;

/**
 * Created by vladimirpapin on 22.06.16.
 */
public interface ConstantManager {
    String TAG_PREFIX = "DEV ";
    String EDIT_MODE_KEY = "EDIT_MODE_KEY";

    String USER_NAME_KEY = "USER_NAME_KEY";
    String USER_PHONE_KEY = "USER_PHONE_KEY";
    String USER_MAIL_KEY = "USER_MAIL_KEY";
    String USER_VK_KEY = "USER_VK_KEY";
    String USER_GIT_KEY = "USER_GIT_KEY";
    String USER_ABOUT_KEY = "USER_ABOUT_KEY";
    String USER_PHOTO_KEY = "USER_PHOTO_KEY";
    String USER_AVATAR_KEY = "USER_AVATAR_KEY";
    String NULL_SHARE_PREFERENCES = "aaaaa123566";
    String LOGIN_KEY = "LOGIN_KEY";
    String AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY";
    String USER_ID_KEY = "USER_ID_KEY";
    String USER_RAITING_VALUE = "USER_RAITING_VALUE";
    String USER_CODE_LINES_VALUE = "USER_CODE_LINES_VALUE";
    String USER_PROJECT_VALUE = "USER_PROJECT_VALUE";

    int LOAD_PROFILE_PHOTO = 100;
    int REQUEST_CAMERA_PICTURE = 110;
    int REQUEST_GALLERY_PICTURE = 115;
    int PERMITION_REQUEST_SETTING_CODE = 880;
    int CAMERA_REQUEST_PERMITION_CODE = 881;
    int SEND_SMS_REQUEST_PERMITION_CODE = 883;
    int CALL_PHONE_REQUEST_PERMITION_CODE = 882;
    int REQUEST_LOGIN_CODE = 300;
}
